version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    image: andreytsay/kittygram_backend:latest
    env_file: .env
    depends on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    env_file: .env
    image: andreytsay/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends on:
      - backend
      
  gateway:
    image: andreytsay/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - 9000:80
    depends on:
      - frontend